### ISSUE TITLE
최종 기능 테스팅 

### ISSUE THREAD

**Issue by sanchaehwa** [sanchaehwa/Team2-6_Project#10]

**Comment by GithubOfHermes** [comment]
![Image](https://github.com/user-attachments/assets/8d7b9bdd-fbf1-4df9-a1dc-1d7b2c04cc1b)
최종 기능 테스트 이상 없음

**Comment by DriedSlime** [comment]
![스크린샷 2024-11-15 202641](https://github.com/user-attachments/assets/6dead10e-d31c-46d4-8a2e-d2aefd7dfc50)
![스크린샷 2024-11-15 202709](https://github.com/user-attachments/assets/e2c2665c-9159-4971-b14d-971eeb6b9090)
테스트 정상 작동

**Comment by sanchaehwa** [comment]
![스크린샷 2024-11-15 오후 8 51 46](https://github.com/user-attachments/assets/385c899e-9350-4d07-b7f8-9f252bb2be54)
 기능 최종 테스트 결과 : 정상 작동
